version: '3.8'
services:
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-db: